## TF Fundamentals Review 

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


**Creating tensors**

In [2]:
#creating rank 0/scalar 
scalar = tf.constant(9)
print(scalar.ndim) #check dimension 
print(scalar)

0
tf.Tensor(9, shape=(), dtype=int32)


In [3]:
#creating a vector (highter than rank/dim 0)
vector = tf.constant([10,10])
print(vector.ndim)
print(vector)

1
tf.Tensor([10 10], shape=(2,), dtype=int32)


In [4]:
#creating a matrix 
matrix = tf.constant([[10,7],
                     [7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


*By default, TensorFlow creates tensors with either an int32 or float32 datatype*

In [5]:
#creating another matrix with its datatype 
matrix_2 = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype = tf.float16)
print(matrix_2.ndim)
print(matrix_2)

2
tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)


*Even though another_matrix contains more numbers, its dimensions stay the same*

In [6]:
#show tensor more than 2 dimension (all items in the previous lines are also tensors, 
#just different ranks)

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
print(tensor.ndim)
print(tensor)

3
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


A tensor can have an arbitrary number of dimensions. <br>
An example of an image turned into a tensor of shape (224,224,3,32) consist of:
- 224,224 are the height and width of the images in pixels 
- 3 is the number of color channel (RGB)
- 32 is the batch size (number of images a NN sees at any particular time) 
<br>

Definitions of tensors with different dimensions:
- scalar: a single number 
- vector: a number with direction (just like physics typical example, wind speed with direction)
- matrix: a 2D array of numbers 
- tensor: a n-dim array of numbers where n can be any number

**Creating tensors with tf.variable**

In [7]:
#compare tensors from tf.variable and tf.constant
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
#try changing one 
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [9]:
# Won't error
# To change an element of a tf.Variable() tensor requires the assign() method.
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(7)
unchangleable_tensor

AttributeError: ignored

**Creating random tensors**

In [11]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [12]:
#shuffling a tensor (valuable when you want to shuffle data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
#gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [13]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

The numbers did not come out the same due to rule #4 of the tf.random.set_seed() documentation. <br>

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.



In [23]:
#set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

#set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

**Other ways to make tensors**

In [24]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [26]:
#numpy can be converted to tensors 
import numpy as np

numpy_A = np.arange(1,25, dtype = np.int32) 
A = tf.constant(numpy_A,
                shape = [2,4,3]) #shape total has to match the number of elements in array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

**Getting information from tensors (shape, rank, size)**

Tensor vocabulary:
- Shape: length of each dimensions of a vector
- Rank: number of tensor dimensions
- Axis/Dimension: Particular dimension of a tensor 
- Size: Total number of items in tensor

In [27]:
#create rank 4 tensor 
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
#get various attributes of tensor 
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [32]:
#indexing tensors like Python list 

#get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [33]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [35]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

#You can achieve the same using tf.expand_dims().

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [36]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

**Manipulating tensors (tensor operations)**

**Basic Operations**

In [37]:
#add values to tensor using addition 
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [40]:
print(tensor * 10)
print(tensor - 10)
print(tf.multiply(tensor,10))

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


**Matrix Multiplication**

In [42]:
print(tensor)
print(tf.matmul(tensor, tensor))
print(tensor@tensor) #same thing with the line before 

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [43]:
#what if we create a mismmatched shaped tensors and multiply them? 
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X@Y

InvalidArgumentError: ignored

Need to either:
- Reshape X to (2,3) so it's (2,3) @ (3,2) 
- Reshape Y to (3,2) so it's (3,2) @ (2,3) <br>
Using tf.reshape() or tf.transpose()

In [44]:
#example of reshape
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [45]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [46]:
#example of transpose 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [47]:
#can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Dot Product**<br>
Performed using tf.tensordot()

In [48]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Difference between tf.transpose and tf.reshape**

In [49]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [50]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [52]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


This can be explained by the default behaviour of each method:

- tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
- tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter. <br>

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

### Exercises from Daniel Bourke's course 

In [ ]:
#1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [ ]:
#2. Find the shape, rank and size of the tensors you created in step 1.

In [ ]:
#3. Create two tensors containing random values between 0 and 1 with shape [5,300].

In [ ]:
#4. Multiply the two tensors you created in step 3 using matrix multiplication.

In [ ]:
#5. Multiply the two tensors you created in step 3 using dot product. 

In [ ]:
#6. Create a tensor with random values between 0 and 1 with shape [224,224,3].

In [ ]:
#7. Find the min and max values of the tensor you created in step 6. 

In [ ]:
#8. Created a tensor with random values of shape [1,224,224,3] then squeeze it to change the shape to [224,224,3]

In [ ]:
#9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [ ]:
#10. One-hot encode the tensor created in step 9. 