## TF Fundamentals Review 

In [6]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.4.1


**Creating tensors**

In [ ]:
#creating rank 0/scalar 
scalar = tf.constant(9)
print(scalar.ndim) #check dimension 
print(scalar)

0
tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
#creating a vector (highter than rank/dim 0)
vector = tf.constant([10,10])
print(vector.ndim)
print(vector)

1
tf.Tensor([10 10], shape=(2,), dtype=int32)


In [ ]:
#creating a matrix 
matrix = tf.constant([[10,7],
                     [7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


*By default, TensorFlow creates tensors with either an int32 or float32 datatype*

In [ ]:
#creating another matrix with its datatype 
matrix_2 = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype = tf.float16)
print(matrix_2.ndim)
print(matrix_2)

2
tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)


*Even though another_matrix contains more numbers, its dimensions stay the same*

In [ ]:
#show tensor more than 2 dimension (all items in the previous lines are also tensors, 
#just different ranks)

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
print(tensor.ndim)
print(tensor)

3
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


A tensor can have an arbitrary number of dimensions. <br>
An example of an image turned into a tensor of shape (224,224,3,32) consist of:
- 224,224 are the height and width of the images in pixels 
- 3 is the number of color channel (RGB)
- 32 is the batch size (number of images a NN sees at any particular time) 
<br>

Definitions of tensors with different dimensions:
- scalar: a single number 
- vector: a number with direction (just like physics typical example, wind speed with direction)
- matrix: a 2D array of numbers 
- tensor: a n-dim array of numbers where n can be any number

**Creating tensors with tf.variable**

In [ ]:
#compare tensors from tf.variable and tf.constant
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#try changing one 
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# Won't error
# To change an element of a tf.Variable() tensor requires the assign() method.
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(7)
unchangleable_tensor

**Creating random tensors**

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuffling a tensor (valuable when you want to shuffle data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
#gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

The numbers did not come out the same due to rule #4 of the tf.random.set_seed() documentation. <br>

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.



In [ ]:
#set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

#set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

**Other ways to make tensors**

In [ ]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
#numpy can be converted to tensors 
import numpy as np

numpy_A = np.arange(1,25, dtype = np.int32) 
A = tf.constant(numpy_A,
                shape = [2,4,3]) #shape total has to match the number of elements in array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

**Getting information from tensors (shape, rank, size)**

Tensor vocabulary:
- Shape: length of each dimensions of a vector
- Rank: number of tensor dimensions
- Axis/Dimension: Particular dimension of a tensor 
- Size: Total number of items in tensor

In [ ]:
#create rank 4 tensor 
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attributes of tensor 
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
#indexing tensors like Python list 

#get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

#You can achieve the same using tf.expand_dims().

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

**Manipulating tensors (tensor operations)**

**Basic Operations**

In [ ]:
#add values to tensor using addition 
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
print(tensor * 10)
print(tensor - 10)
print(tf.multiply(tensor,10))

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


**Matrix Multiplication**

In [ ]:
print(tensor)
print(tf.matmul(tensor, tensor))
print(tensor@tensor) #same thing with the line before 

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [ ]:
#what if we create a mismmatched shaped tensors and multiply them? 
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X@Y

InvalidArgumentError: ignored

Need to either:
- Reshape X to (2,3) so it's (2,3) @ (3,2) 
- Reshape Y to (3,2) so it's (3,2) @ (2,3) <br>
Using tf.reshape() or tf.transpose()

In [ ]:
#example of reshape
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#example of transpose 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Dot Product**<br>
Performed using tf.tensordot()

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Difference between tf.transpose and tf.reshape**

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [ ]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


This can be explained by the default behaviour of each method:

- tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
- tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter. <br>

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

**Changing datatype of tensor**

Sometimes you'll want to alter the default datatype of the tensor. <br>
This is common when you want to compute using less precision (16 bit vs 32 bit), which is useful on devices with less computing capacity.

In [ ]:
#create tensor with default datatypes float32 and int32
B = tf.constant([1.7, 7.4])
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
#change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
#change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

**Getting absolute value**

In [ ]:
D = tf.constant([-7, -10])
print(D)
tf.abs(D)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Aggregation of tensors**

In [ ]:
#create tensor with 50 random values 0<x<100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([62, 70, 73, 62, 85, 23, 68, 20, 99, 43, 76, 31, 32,  7, 29, 10, 58,
       59, 96, 81, 26, 12, 83, 92, 79, 64, 45, 56, 50, 11, 75,  6, 40, 46,
        2, 62, 35,  9, 11, 35, 72, 17, 28, 40,  4, 82, 75,  6, 57, 56])>

In [ ]:
print('Tensor min: ',tf.reduce_min(E))
print('Tensor max: ',tf.reduce_max(E))
print('Tensor mean: ',tf.reduce_mean(E))
print('Tensor sum: ',tf.reduce_sum(E))

Tensor min:  tf.Tensor(2, shape=(), dtype=int64)
Tensor max:  tf.Tensor(99, shape=(), dtype=int64)
Tensor mean:  tf.Tensor(47, shape=(), dtype=int64)
Tensor sum:  tf.Tensor(2360, shape=(), dtype=int64)


**Finding positional max and min**

In [ ]:
#create tensor with 50 values 0<x<1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.70735909, 0.41026854, 0.54640903, 0.04342883, 0.65905056,
       0.5750152 , 0.82714485, 0.39079024, 0.10954115, 0.66846346,
       0.81662315, 0.28896981, 0.97044031, 0.96918533, 0.00390682,
       0.44412675, 0.93841695, 0.62146514, 0.04396715, 0.07655684,
       0.39174026, 0.94003616, 0.26738483, 0.07491914, 0.98877898,
       0.97200571, 0.24107296, 0.98761418, 0.56637123, 0.08094821,
       0.80681326, 0.03747839, 0.11958671, 0.59379724, 0.423332  ,
       0.66811672, 0.2793807 , 0.87546655, 0.76142896, 0.07482479,
       0.40835369, 0.92126832, 0.77821355, 0.83235425, 0.55623488,
       0.5817211 , 0.85737382, 0.87844154, 0.55928119, 0.39163425])>

In [ ]:
print(tf.argmax(F)) #positional maximum
print(tf.argmin(F)) #positional minimum 

tf.Tensor(24, shape=(), dtype=int64)
tf.Tensor(14, shape=(), dtype=int64)


In [ ]:
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
#proof
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 24
The maximum value of F is: 0.9887789823474505
Using tf.argmax() to index F, the maximum value of F is: 0.9887789823474505
Are the two max values the same (they should be)? True


**Squeezing Tensor**

In [ ]:
#create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim, G

(TensorShape([1, 1, 1, 1, 50]),
 5,
 <tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
 array([[[[[96, 75, 29, 72, 90, 17, 79, 22, 67, 54, 34,  8, 16, 89, 67,
             0, 68, 17, 59, 14, 92, 13, 50, 95, 54, 65, 81, 50, 24, 19,
             0, 38, 73, 79, 98, 11, 90, 19, 13, 21, 37,  1, 20, 74, 13,
             0,  8,  8, 72, 68]]]]])>)

In [ ]:
#squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim, G_squeezed

(TensorShape([50]), 1, <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([96, 75, 29, 72, 90, 17, 79, 22, 67, 54, 34,  8, 16, 89, 67,  0, 68,
        17, 59, 14, 92, 13, 50, 95, 54, 65, 81, 50, 24, 19,  0, 38, 73, 79,
        98, 11, 90, 19, 13, 21, 37,  1, 20, 74, 13,  0,  8,  8, 72, 68])>)

**One-hot encoding**

In [ ]:
#list of indices
some_list = [0,1,2,3]
#one hot encode the list 
tf.one_hot(some_list, depth=4) #depth is the level of which you want to one-hot encode to 

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#you can also specify custom values for on and off encoding with strings 
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

**Square log & Square root**

**Manipulating tf.Variable tensors**

**Tensors & Numpy**

**Using tf.function**

**Access GPU! (important part!!!)**

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
#find info about the GPU using nvidia-smi
!nvidia-smi

Tue Mar  2 20:24:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Exercises from Daniel Bourke's course 

In [ ]:
#1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
vector_A = tf.constant([1,2,3])
scalar_A = tf.constant([7])
matrix_A = tf.constant([[8,8],
                        [9,9]])
tensor_A = tf.constant([[[1,2,3],
                         [4,5,6]],
                        [[7,8,9],
                         [10,11,12]]])

vector_A, scalar_A, matrix_A, tensor_A

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[8, 8],
        [9, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [ ]:
#2. Find the shape, rank and size of the tensors you created in step 1.
print(vector_A.shape, vector_A.ndim, tf.size(vector_A))
print(scalar_A.shape, scalar_A.ndim, tf.size(scalar_A))
print(matrix_A.shape, matrix_A.ndim, tf.size(matrix_A))
print(tensor_A.shape, tensor_A.ndim, tf.size(tensor_A))

(3,) 1 tf.Tensor(3, shape=(), dtype=int32)
(1,) 1 tf.Tensor(1, shape=(), dtype=int32)
(2, 2) 2 tf.Tensor(4, shape=(), dtype=int32)
(2, 2, 3) 3 tf.Tensor(12, shape=(), dtype=int32)


In [8]:
#3. Create two tensors containing random values between 0 and 1 with shape [5,300].
tensor_B = tf.constant(np.random.random(1500), shape=(5,300))
tensor_C = tf.constant(np.random.random(1500), shape=(5,300))
tensor_B.shape, tensor_C.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [11]:
#4. Multiply the two tensors you created in step 3 using matrix multiplication.
tensorBC_mul = tf.matmul(tensor_B,tf.transpose(tensor_C))
tensorBC_mul

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[76.52517941, 73.71508718, 74.74622611, 71.42191439, 74.33287376],
       [79.30000554, 77.89902684, 78.53796934, 76.9968161 , 76.66709073],
       [83.53407547, 80.88574805, 79.6106507 , 81.26113862, 79.14432687],
       [77.83454623, 77.80947404, 73.21546977, 77.06702076, 74.14553682],
       [74.05581561, 74.35912739, 73.66434321, 76.96258319, 71.41476813]])>

In [21]:
#5. Multiply the two tensors you created in step 3 using dot product. 
tensorBC_dot1 = tf.tensordot(tensor_B, tf.transpose(tensor_C), axes=1)
tensorBC_dot2 = tf.tensordot(tensor_B, tensor_C, axes=0) #will do an outer product, leading to a tensor of order 4 
tensorBC_dot1.shape, tensorBC_dot2.shape

(TensorShape([5, 5]), TensorShape([5, 300, 5, 300]))

Can watch explanation of inner vs outer product [here](https://www.youtube.com/watch?v=FCmH4MqbFGs&ab_channel=JeffreyChasnov). 

In [19]:
#6. Create a tensor with random values between 0 and 1 with shape [224,224,3].
tensor_D = tf.constant(np.random.random(224*224*3),shape=(224,224,3))
tensor_D.shape

TensorShape([224, 224, 3])

In [22]:
#7. Find the min and max values of the tensor you created in step 6. 
tensor_D_min = tf.reduce_min(tensor_D)
tensor_D_max = tf.reduce_max(tensor_D)
tensor_D_min, tensor_D_max

(<tf.Tensor: shape=(), dtype=float64, numpy=7.34226893606138e-06>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.9999972280491642>)

In [24]:
#8. Created a tensor with random values of shape [1,224,224,3] then squeeze it to change the shape to [224,224,3]
tensor_E = tf.constant(np.random.randint(low=0, high=100, size=1*224*224*3), shape=(1,224,224,3))
tensor_E_squeeze = tf.squeeze(tensor_E)
tensor_E.shape, tensor_E_squeeze.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [26]:
#9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value
tensor_F = tf.constant(np.random.randint(low=0, high = 78, size=10), shape=(10))
tensor_F_argmax = tf.argmax(tensor_F)
tensor_F[tensor_F_argmax].numpy(), tf.reduce_max(tensor_F) #access the value in both ways (proof that it has the same value)

(75, <tf.Tensor: shape=(), dtype=int64, numpy=75>)

In [29]:
#10. One-hot encode the tensor created in step 9. 
one_hot_F = tf.one_hot(tensor_F, depth=78)
one_hot_F

<tf.Tensor: shape=(10, 78), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 

## Extra practice from D. Bourke

In [2]:
#Read through the list of TensorFlow Python APIs, 
#pick one we haven't gone through in this notebook, 
#reverse engineer it

#chosen API:

In [3]:
#Try to create a series of tensor functions to 
#calculate your most recent grocery bill 

In [4]:
#Go through the TensorFlow 2.x quick start for beginners tutorial
#Are there any functions we used in here that match what's used in there?

In [ ]:
#Watch video of What's a tensor