## TF Fundamentals Review 

In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.3


**Creating tensors**

In [4]:
#creating rank 0/scalar 
scalar = tf.constant(9)
print(scalar.ndim) #check dimension 
print(scalar)

0
tf.Tensor(9, shape=(), dtype=int32)


In [6]:
#creating a vector (highter than rank/dim 0)
vector = tf.constant([10,10])
print(vector.ndim)
print(vector)

1
tf.Tensor([10 10], shape=(2,), dtype=int32)


In [10]:
#creating a matrix 
matrix = tf.constant([[10,7],
                     [7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


*By default, TensorFlow creates tensors with either an int32 or float32 datatype*

In [12]:
#creating another matrix with its datatype 
matrix_2 = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype = tf.float16)
print(matrix_2.ndim)
print(matrix_2)

2
tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)


*Even though another_matrix contains more numbers, its dimensions stay the same*

In [13]:
#show tensor more than 2 dimension (all items in the previous lines are also tensors, 
#just different ranks)

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
print(tensor.ndim)
print(tensor)

3
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


A tensor can have an arbitrary number of dimensions. <br>
An example of an image turned into a tensor of shape (224,224,3,32) consist of:
- 224,224 are the height and width of the images in pixels 
- 3 is the number of color channel (RGB)
- 32 is the batch size (number of images a NN sees at any particular time) 
<br>

Definitions of tensors with different dimensions:
- scalar: a single number 
- vector: a number with direction (just like physics typical example, wind speed with direction)
- matrix: a 2D array of numbers 
- tensor: a n-dim array of numbers where n can be any number

**Creating tensors with tf.variable**

In [14]:
#compare tensors from tf.variable and tf.constant
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#try changing one 

**Creating random tensors**

**Other ways to make tensors**

**Getting information from tensors (shape, rank, size)**

**Manipulating tensors (tensor operations)**

### Exercises from Daniel Bourke's course 

In [15]:
#1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [17]:
#2. Find the shape, rank and size of the tensors you created in step 1.

In [18]:
#3. Create two tensors containing random values between 0 and 1 with shape [5,300].

In [20]:
#4. Multiply the two tensors you created in step 3 using matrix multiplication.

In [22]:
#5. Multiply the two tensors you created in step 3 using dot product. 

In [23]:
#6. Create a tensor with random values between 0 and 1 with shape [224,224,3].

In [24]:
#7. Find the min and max values of the tensor you created in step 6. 

In [25]:
#8. Created a tensor with random values of shape [1,224,224,3] then squeeze it to change the shape to [224,224,3]

In [26]:
#9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [27]:
#10. One-hot encode the tensor created in step 9. 